In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df=pd.read_excel(r"C:\Users\Asus\OneDrive\Desktop\S-Dataset\Retail_Database.xlsx",sheet_name="customers")

In [7]:
df.head()

,customer_id,customer_name,gender,age,city,state,region,join_date
0,1,Customer_00001,Male,65,Pune,Maharashtra,West,2021-06-27
1,2,Customer_00002,Male,28,Delhi,Delhi,North,2025-05-26
2,3,Customer_00003,Female,65,Mumbai,Maharashtra,West,2019-12-31
3,4,Customer_00004,Male,45,Chennai,Tamil Nadu,South,2021-12-25
4,5,Customer_00005,Male,27,Noida,Uttar Pradesh,North,2021-08-16

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   int64
 1   customer_name  5000 non-null   object
 2   gender         5000 non-null   object
 3   age            5000 non-null   int64
 4   city           5000 non-null   object
 5   state          5000 non-null   object
 6   region         5000 non-null   object
 7    join_date     5000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 312.6+ KB

In [11]:
df.describe()

       customer_id            age                   join_date
count    5000.000000  5000.000000                        5000
mean     2500.500000    41.381400  2022-06-25 04:25:49.440000
min         1.000000    18.000000         2019-01-01 00:00:00
25%      1250.750000    29.000000         2020-09-16 12:00:00
50%      2500.500000    41.000000         2022-06-05 00:00:00
75%      3750.250000    54.000000         2024-04-16 00:00:00
max      5000.000000    65.000000         2026-02-04 00:00:00
std      1443.520003    13.868843                         NaN

In [12]:
df.isna()

,customer_id,customer_name,gender,age,city,state,region,join_date
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False

In [13]:
df=pd.read_excel(r"C:\Users\Asus\OneDrive\Desktop\S-Dataset\Retail_Database.xlsx",sheet_name="products")

In [14]:
df

,productid,product_name,category,subcategory,cost_price,selling_price
0,101,Product_101,Grocery,Staples,200,500
1,102,Product_102,Fashion,Footwear,2500,2800
2,103,Product_103,Grocery,Staples,200,500
3,104,Product_104,Grocery,Staples,200,500
4,105,Product_105,Fashion,Footwear,2500,2800
...,...,...,...,...,...,...
495,596,Product_596,Electronics,Television,50000,50300
496,597,Product_597,Electronics,Television,50000,50300
497,598,Product_598,Electronics,Television,50000,50300
498,599,Product_599,Grocery,Staples,200,500
499,600,Product_600,Electronics,Television,50000,50300

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   productid      500 non-null    int64
 1   product_name   500 non-null    object
 2   category       500 non-null    object
 3   subcategory    500 non-null    object
 4   cost_price     500 non-null    int64
 5   selling_price  500 non-null    int64
dtypes: int64(3), object(3)
memory usage: 23.6+ KB

In [16]:
df.isna()

     productid  product_name  category  subcategory  cost_price  selling_price
0        False         False     False        False       False          False
1        False         False     False        False       False          False
2        False         False     False        False       False          False
3        False         False     False        False       False          False
4        False         False     False        False       False          False
..         ...           ...       ...          ...         ...            ...
495      False         False     False        False       False          False
496      False         False     False        False       False          False
497      False         False     False        False       False          False
498      False         False     False        False       False          False
499      False         False     False        False       False          False

[500 rows x 6 columns]

In [17]:
df.describe()

        productid    cost_price  selling_price
count  500.000000    500.000000     500.000000
mean   350.500000  17439.000000   17739.000000
std    144.481833  22893.882123   22893.882123
min    101.000000    200.000000     500.000000
25%    225.750000    200.000000     500.000000
50%    350.500000   2500.000000    2800.000000
75%    475.250000  50000.000000   50300.000000
max    600.000000  50000.000000   50300.000000

In [19]:
df=pd.read_excel(r"C:\Users\Asus\OneDrive\Desktop\S-Dataset\Retail_Database.xlsx",sheet_name="stores")

In [20]:
df.head()

   store_id store_name    city         state region manager_name
0         1   Store_01     Pune  Maharashtra   West   Manager_01
1         2   Store_02  Kolkata  West Bengal   East   Manager_02
2         3   Store_03   Mumbai  Maharashtra   West   Manager_03
3         4   Store_04   Mumbai  Maharashtra   West   Manager_04
4         5   Store_05  Kolkata  West Bengal   East   Manager_05

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      50 non-null     int64
 1   store_name    50 non-null     object
 2   city          50 non-null     object
 3   state         50 non-null     object
 4   region        50 non-null     object
 5   manager_name  50 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.5+ KB

In [22]:
df.isna()

    store_id  store_name  city   state  region  manager_name
0      False       False  False  False   False         False
1      False       False  False  False   False         False
2      False       False  False  False   False         False
3      False       False  False  False   False         False
4      False       False  False  False   False         False
5      False       False  False  False   False         False
6      False       False  False  False   False         False
7      False       False  False  False   False         False
8      False       False  False  False   False         False
9      False       False  False  False   False         False
10     False       False  False  False   False         False
11     False       False  False  False   False         False
12     False       False  False  False   False         False
13     False       False  False  False   False         False
14     False       False  False  False   False         False
15     False       False  False  False   False         False
16     False       False  False  False   False         False
17     False       False  False  False   False         False
18     False       False  False  False   False         False
19     False       False  False  False   False         False
20     False       False  False  False   False         False
21     False       False  False  False   False         False
22     False       False  False  False   False         False
23     False       False  False  False   False         False
24     False       False  False  False   False         False
25     False       False  False  False   False         False
26     False       False  False  False   False         False
27     False       False  False  False   False         False
28     False       False  False  False   False         False
29     False       False  False  False   False         False
30     False       False  False  False   False         False
31     False       False  False  False   False         False
32     False       False  False  False   False         False
33     False       False  False  False   False         False
34     False       False  False  False   False         False
35     False       False  False  False   False         False
36     False       False  False  False   False         False
37     False       False  False  False   False         False
38     False       False  False  False   False         False
39     False       False  False  False   False         False
40     False       False  False  False   False         False
41     False       False  False  False   False         False
42     False       False  False  False   False         False
43     False       False  False  False   False         False
44     False       False  False  False   False         False
45     False       False  False  False   False         False
46     False       False  False  False   False         False
47     False       False  False  False   False         False
48     False       False  False  False   False         False
49     False       False  False  False   False         False

In [23]:
df.describe()

       store_id
count  50.00000
mean   25.50000
std    14.57738
min     1.00000
25%    13.25000
50%    25.50000
75%    37.75000
max    50.00000

In [24]:
df=pd.read_excel(r"C:\Users\Asus\OneDrive\Desktop\S-Dataset\Retail_Database.xlsx",sheet_name="inventory")

In [25]:
df.head()

   inventory_id   product_id  store_id   stock_received_date  stock_quantity
0              1         261         42           2023-08-30             368
1              2         355         20           2019-11-10             457
2              3         476         33           2025-06-10             351
3              4         320          6           2024-08-03             186
4              5         564         39           2025-05-12             208

In [26]:
df.isna()

,inventory_id,product_id,store_id,stock_received_date,stock_quantity
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
1995,False,False,False,False,False
1996,False,False,False,False,False
1997,False,False,False,False,False
1998,False,False,False,False,False
1999,False,False,False,False,False

In [27]:
df.describe()

,inventory_id,product_id,store_id,stock_received_date,stock_quantity
count,2000.000000,2000.000000,2000.000000,2000,2000.000000
mean,1000.500000,351.931000,25.351500,2022-01-16 16:58:48,256.136000
min,1.000000,101.000000,1.000000,2018-01-04 00:00:00,10.000000
25%,500.750000,225.000000,12.000000,2020-01-12 18:00:00,137.750000
50%,1000.500000,357.000000,25.000000,2022-01-24 00:00:00,257.000000
75%,1500.250000,475.000000,38.000000,2024-01-30 06:00:00,374.250000
max,2000.000000,600.000000,50.000000,2026-02-04 00:00:00,500.000000
std,577.494589,144.339611,14.544611,NaN,140.379007

In [28]:
df=pd.read_excel(r"C:\Users\Asus\OneDrive\Desktop\S-Dataset\Retail_Database.xlsx",sheet_name="sales")

In [29]:
df.head()

,sale_id,sale_date,customer_id,product_id,store_id,quantity,discount,payment_mode
0,1,2024-09-21,4268,130,1,5,17,Credit Card
1,2,2021-05-05,2107,315,48,2,12,Debit Card
2,3,2020-10-08,3408,509,50,1,16,Debit Card
3,4,2022-05-27,1271,389,10,2,2,Credit Card
4,5,2025-06-09,4000,253,23,1,6,Credit Card

In [30]:
df.isna()

,sale_id,sale_date,customer_id,product_id,store_id,quantity,discount,payment_mode
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False

In [31]:
df.describe()

,sale_id,sale_date,customer_id,product_id,store_id,quantity,discount
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,2022-07-28 05:53:39.840000,2466.619400,351.953800,25.357000,3.015000,10.008200
min,1.000000,2019-01-01 00:00:00,2.000000,101.000000,1.000000,1.000000,0.000000
25%,1250.750000,2020-10-20 00:00:00,1232.750000,224.750000,13.000000,2.000000,5.000000
50%,2500.500000,2022-08-14 12:00:00,2425.500000,351.000000,25.000000,3.000000,10.000000
75%,3750.250000,2024-05-11 06:00:00,3703.250000,477.000000,38.000000,4.000000,15.000000
max,5000.000000,2026-02-04 00:00:00,4997.000000,600.000000,50.000000,5.000000,20.000000
std,1443.520003,NaN,1432.360306,145.473158,14.456159,1.413214,6.104194